site_name: 'Documentazione Super Progetto'
docs_dir: '../../docs/it'                           # Where to find the markdown files
site_dir: '../../generated/it'                           # Where to put the HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                   # This is where the customization of the theme lives
    logo: assets/images/logo.png                     # The logo is shared by all languages
    favicon: assets/images/favicon.ico               # The favicon is shared by all languages
    language: it                    # The build's language
    features:
    - navigation.top
    - search.highlight
    - search.suggest
extra_css:
  - assets/stylesheets/eng-standard-theme.css                   # CSS is shared by all languages
  - assets/stylesheets/fabric.min.css 
  - assets/stylesheets/toc.css 
  - assets/stylesheets/language-switcher.css                    # Language switcher styles

extra_javascript:
  - assets/js/toc.js  
  - assets/js/language-switcher.js                              # Language switcher functionality

plugins:
  - search:
      lang: it                       # Set language for search
  - render_swagger:
      css: swagger-ui.css           # Correctly indented plugin config
  - print-site:
      add_to_navigation: false
      print_page_title: 'Stampa'
      add_table_of_contents: false
      toc_title: 'Indice dei contenuti'
      toc_depth: 6
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

nav:
- "<span class='ms-Icon ms-Icon--WaitlistConfirm'></span> Installazione e deploy": Getting started.md
- "<span class='ms-Icon ms-Icon--AuthenticatorApp'></span> Authentication": Authentication.md
- "<span class='ms-Icon ms-Icon--ModelingView'></span> Tenant Management": Gestione Tenant.md
- "<span class='ms-Icon ms-Icon--Admin'></span> Administration": Administration.md
- "<span class='ms-Icon ms-Icon--ViewDashboard'></span> Dashboard": Dashboard.md
- "<span class='ms-Icon ms-Icon--OpenFolderHorizontal'></span> Inventory": Inventory.md
- "<span class='ms-Icon ms-Icon--AreaChart'></span> Monitoring": Monitoring.md
- "<span class='ms-Icon ms-Icon--AzureKeyVault'></span> Security": Security.md
- "<span class='ms-Icon ms-Icon--AddToShoppingList'></span> Catalog": Catalog.md
- "<span class='ms-Icon ms-Icon--Money'></span> Costs & Usage": Costs e Usage.md
- "<span class='ms-Icon ms-Icon--BranchFork2'></span> Provisioning": Provisioning.md
- "<span class='ms-Icon ms-Icon--Lifesaver'></span> Backup & Disaster Recovery": Backup Disaster Recovery.md
- "<span class='ms-Icon ms-Icon--SecondaryNav'></span> Shared Features": Funzionalit√† condivise.md
- "<span class='ms-Icon ms-Icon--ReservationOrders'></span> Service Detail Design": Service Detail Design.md
- "<span class='ms-Icon ms-Icon--AddToShoppingList'></span> Leonardo Services": OverviewPSN.md
- "<span class='ms-Icon ms-Icon--AzureAPIManagement'></span> REST API":
  - "Finops": api/finopsAPI.md
  - "Provisioning": api/provisioningAPI.md
  - "Inventory / Catalog": api/rmAPI.md
  - "Abstraction Layer": api/absAPI.md
  - "Report manager": api/rmreportAPI.md
  - "Cost": api/rmcostsAPI.md
  - "Monitoring": api/rmmonitoringAPI.md
  - "Security": api/rmsecurityAPI.md
  - "Services": api/rmserviceAPI.md
  - "SIEM": api/siemAPI.md
  - "Taxonomy Manager": api/txmAPI.md
  - "Tenant Manager": api/tenantAPI.md
  - "Service detail design": api/api.md
- "<span class='ms-Icon ms-Icon--PDF'></span> Versione PDF completa": SCMP_SUM_it.pdf


markdown_extensions:
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.superfences